version: '3.8'
services:
  postgresql:
    image: postgres:16.2

    environment:
      - POSTGRES_USER=marek
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '127.0.0.1:5432:5432'
